name: Metrics
on:
  schedule: [{cron: "0 * * * *"}]  # läuft jede Stunde
  workflow_dispatch:               # manuelles Auslösen möglich
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories, metadata
